# Generated by Django 3.1.6 on 2021-03-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApp', '0004_auto_20210319_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
